/obj/structure/closet/secure_closet/engineering_chief/PopulateContents()
	..()
	new /obj/item/clothing/neck/cloak/ce(src)
	new /obj/item/clothing/head/beret/ce(src)
	new /obj/item/clothing/under/rank/engineering/chief_engineer(src)
	new /obj/item/clothing/under/rank/engineering/chief_engineer/skirt(src)
	new /obj/item/clothing/head/hardhat/white(src)
	new /obj/item/clothing/head/hardhat/weldhat/white(src)
	new /obj/item/clothing/gloves/color/yellow(src)
	new /obj/item/tank/jetpack/suit(src)
	new /obj/item/cartridge/ce(src)
	new /obj/item/radio/headset/heads/ce(src)
	new /obj/item/megaphone/command(src)
	new /obj/item/areaeditor/blueprints(src)
	new /obj/item/holosign_creator/engineering(src)
	new /obj/item/assembly/flash/handheld(src)
	new /obj/item/clothing/glasses/meson/engine(src)
	new /obj/item/door_remote/chief_engineer(src)
	new /obj/item/inducer(src)
	new /obj/item/circuitboard/machine/techfab/department/engineering(src)
	new /obj/item/extinguisher/advanced(src)
	new /obj/item/storage/photo_album/CE(src)
	new	/obj/item/storage/lockbox/medal/engineering(src)
	new /obj/item/construction/rcd/experimental(src)
	new /obj/item/clothing/suit/hooded/wintercoat/ce(src)
	new /obj/item/clothing/head/beret/ce/white(src)
	new /obj/item/storage/bag/construction(src)
	new /obj/item/storage/bag/material(src)
